name: 'Setup Node.js'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          .yarn/cache
          .yarn/install-state.gz
          .eslintcache
          **/tsconfig.tsbuildinfo
          **/.types/**
          **/.types-*/**
        key: build-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          build-cache-

    - name: Install dependencies
      run: yarn
