main="./dist/worker/worker.mjs"
name = "starknet-website"
compatibility_flags = []
compatibility_date = "2023-07-17"
workers_dev = true
node_compat = true

[site]
bucket = "./dist/client"

[dev]
port = 3000
