name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./actions/node.yml

      - name: Restore Crowdin Cache
        uses: actions/cache/restore@v3
        with:
          path: _crowdin
          key: crowdin-cache-dev

      - name: Update dynamic data
        run: yarn workspace @starknet-io/cms-scripts update-dynamic-data

      - name: Build project
        run: yarn exec next build
