name: Crowdin Action

on:
  - workflow_dispatch

concurrency: crowdin-dev

jobs:
  synchronize-with-crowdin:
    environment: "dev-crowdin"

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn
      - run: yarn workspace @starknet-io/cms-scripts pre-crowdin
      - run: yarn crowdin upload -b ${{ github.ref_name }}
      - run: yarn crowdin download -b ${{ github.ref_name }} --export-only-approved --skip-untranslated-strings
      - uses: actions/cache/save@v3
        with:
          path: _crowdin
          key: crowdin-cache-${{ github.ref_name }}
