name: Crowdin Action

on:
  workflow_dispatch:

concurrency: crowdin-dev

jobs:
  synchronize-with-crowdin:
    name: Synchronize with Crowdin
    environment: "dev-crowdin"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/node.yml

      - name: Restore Crowdin Cache
        uses: actions/cache/restore@v3
        with:
          path: _crowdin
          key: crowdin-cache-${{ github.ref_name }}

      - name: Run pre-Crowdin script for file preparation
        run: yarn workspace @starknet-io/cms-scripts pre-crowdin

      - name: Upload source files to Crowdin project
        run: yarn crowdin upload -b ${{ github.ref_name }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Download approved translations from Crowdin
        run: yarn crowdin download -b ${{ github.ref_name }} --export-only-approved --skip-untranslated-strings
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Save Crowdin Cache
        uses: actions/cache/save@v3
        with:
          path: _crowdin
          key: crowdin-cache-${{ github.ref_name }}
