name: Deploy

on:
  push:
    branches:
      - dev
      - production
      - tsotne/wip

jobs:
  build_and_deploy:
    name: Build and Deploy
    environment: "dev-deploy"
    env:
      ALGOLIA_INDEX: ${{ github.ref_name }}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
      ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_WRITE_API_KEY }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Restore Crowdin cache
        uses: actions/cache@v3
        with:
          path: _crowdin
          key: crowdin-cache-${{ github.ref_name }}

      - name: Install project dependencies
        run: yarn

      - name: Update dynamic data in workspace
        run: yarn workspace @starknet-io/cms-scripts update-dynamic-data

      - name: Update Algolia search index in workspace
        run: yarn workspace @starknet-io/cms-scripts update-algolia-index

      - name: Prepare Vercel environment and build project
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy prebuilt project to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
