name: Build and Deploy Storybook

on:
  push:

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment: "storybook"
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./actions/node.yml

      - name: Build storybook
        run: yarn exec storybook build

      - name: Deploy storybook
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: starknet-storybook
          directory: storybook-static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
