name: Update Jobs

on:
  push:
    branches:
      - jobs-archiving
  schedule:
    - cron: "0 0 * * *" # This will run the workflow every day at midnight

jobs:
  update-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: jobs-archiving
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .eslintcache
            **/tsconfig.tsbuildinfo
            **/.types/**
            **/.types-*/**
          key: build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-cache-

      - name: Install dependencies
        run: yarn

      - name: Run update-jobs script
        run: yarn update-jobs

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@example.com'
          git checkout jobs-archiving
          git checkout -b update-jobs
          git add .
          git commit -m "Update jobs"
          git push origin update-jobs

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Jobs archiving PR"
          pr_body: |
            ## How to approve and merge this pull request

            As a content contributor, follow these steps to review, approve, and merge this pull request:

              - [ ] 1. Review the changes made in this pull request by looking at the "Files changed" tab. Make sure everything looks correct and as expected.
              - [ ] 2. Visit the live preview of the changes at [https://starknet-website-dev.vercel.app/](https://starknet-website-dev.vercel.app/). Ensure the changes are properly implemented and everything is working as expected.
              - [ ] 3. If you are satisfied with the changes, click on the "Review changes" button (usually green) at the top of the pull request page.
              - [ ] 4. In the review summary dialog, select "Approve" and click on "Submit review."
              - [ ] 5. Click on "Confirm merge" to finalize the process. The changes will be applied to the production branch, and [starknet.io](http://starknet.io) will be updated within a few minutes.

              If you are unsure about merging something or need any assistance, please ping a developer to double check.

          pr_allow_empty: false
          pr_label: "auto-pr"
          source_branch: "update-jobs"
          destination_branch: "jobs-archiving"
          github_token: ${{ secrets.GITHUB_TOKEN }}
