name: Update Dynamic Data

on:
  push:
    branches:
      - jobs-archiving

  schedule:
    - cron: "45 13 * * *" # This will run the workflow every day at midnight

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: jobs-archiving
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .eslintcache
            **/tsconfig.tsbuildinfo
            **/.types/**
            **/.types-*/**
          key: build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-cache-

      - name: Install dependencies
        run: yarn

      - name: Run data script
        run: yarn data

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@example.com'
          git checkout jobs-archiving
          git checkout -b update-data
          git add .
          git commit -m "Update dynamic data"
          git push origin update-data

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Update dynamic data"
          pr_body: "This PR updates the dynamic data with the latest changes."
          pr_allow_empty: false
          pr_label: "auto-pr"
          destination_branch: "jobs-archiving"
          github_token: ${{ secrets.GITHUB_TOKEN }}
