name: Build and Deploy Starknet Website

on:
  push:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .eslintcache
            **/tsconfig.tsbuildinfo
            **/.types/**
            **/.types-*/**
          key: build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-cache-

      - name: Install dependencies
        run: yarn

      - name: Restore Crowdin Cache
        uses: actions/cache/restore@v3
        with:
          path: _crowdin
          key: crowdin-cache-dev

      - name: Update dynamic data
        run: yarn workspace @starknet-io/cms-scripts update-dynamic-data

      - name: Build project
        run: yarn workspace @starknet-io/website exec vite build
        env:
          VITE_SITE_URL: https://starknet-website-${{ github.ref_name }}.yukilabs.workers.dev
          VITE_ALGOLIA_INDEX: dev
          VITE_ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          VITE_ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}

      - name: Create Env
        run: echo -e "\n[env.${{ github.ref_name }}]\n" >> workspaces/website/wrangler.toml

      - name: Publish
        run: yarn workspace @starknet-io/website exec wrangler publish --env ${{ github.ref_name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
