name: Build and Deploy Starknet Website

on:
  push:

jobs:
  build:
    name: Build and Deploy
    environment:
      name: Starknet Website ${{ github.ref_name }}
      url: https://starknet-website-${{ env.GITHUB_REF_SLUG }}.yukilabs.workers.dev
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
            .eslintcache
            **/tsconfig.tsbuildinfo
            **/.types/**
            **/.types-*/**
          key: build-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-cache-

      - name: Install dependencies
        run: yarn

      - name: Restore Crowdin Cache
        uses: actions/cache/restore@v3
        with:
          path: _crowdin
          key: crowdin-cache-dev

      - name: Update dynamic data
        run: yarn workspace @starknet-io/cms-scripts update-dynamic-data

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 40

      - name: Create Env
        run: echo -e "\n[env.${{ env.GITHUB_REF_SLUG }}]\n" >> workspaces/website/wrangler.toml

      - name: Create secrets.json
        run: echo '{"YOUTUBE_API_KEY":"${{ secrets.YOUTUBE_API_KEY }}"}' > workspaces/website/secrets.json

      - name: Upload secrets
        run: yarn workspace @starknet-io/website exec wrangler secret:bulk secrets.json --env ${{ env.GITHUB_REF_SLUG }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Build project
        run: yarn workspace @starknet-io/website build
        env:
          VITE_SITE_URL: https://starknet-website-${{ env.GITHUB_REF_SLUG }}.yukilabs.workers.dev
          VITE_ALGOLIA_INDEX: ${{ github.ref_name == 'production' && 'production' || 'dev' }}
          VITE_ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          VITE_ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          VITE_CF_STREAM_URL: ${{ secrets.CF_STREAM_URL }}

      - name: Publish
        run: yarn workspace @starknet-io/website exec wrangler publish --env ${{ env.GITHUB_REF_SLUG }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
